# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sutra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tripitaka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '藏经',
                'verbose_name_plural': '藏经',
            },
        ),
        migrations.RemoveField(
            model_name='page',
            name='name',
        ),
        migrations.AddField(
            model_name='page',
            name='page_no',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='sutra',
            name='qianziwen',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
