# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sutra', '0003_sutra_tripitaka'),
    ]

    operations = [
        migrations.AddField(
            model_name='sutra',
            name='total_reel_no',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sutra',
            name='tripitaka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sutra.Tripitaka'),
        ),
    ]
