# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sutra', '0004_auto_20171206_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='txt',
            field=models.TextField(blank=True),
        ),
    ]
