# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sutra', '0005_page_txt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='Reel',
            new_name='reel',
        ),
    ]
