# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sutra', '0006_auto_20171220_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sutra',
            name='code',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='sutra',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
