# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-23 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sutra', '0007_auto_20171221_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page_no',
            new_name='v_page_no',
        ),
        migrations.AddField(
            model_name='page',
            name='r_page_no',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='v_no',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
