# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sutra', '0008_auto_20171223_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('img_path', models.CharField(max_length=128)),
                ('txt', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '列',
                'verbose_name_plural': '列',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='cut_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='line',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sutra.Page'),
        ),
    ]
