# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sutra', '0011_auto_20180104_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reel',
            name='image_upload',
            field=models.BooleanField(default=False),
        ),
    ]
