# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sutra', '0015_auto_20180106_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='col_no',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
    ]
