# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-13 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sutra', '0016_page_col_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='sutra',
            name='height',
            field=models.IntegerField(blank=True, default=780, verbose_name='图片标准高度'),
        ),
    ]
