# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-13 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sutra', '0017_sutra_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='sutra_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='实体经目编码'),
        ),
    ]
