# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-14 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sutra', '0018_reel_sutra_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OImg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('img_code', models.CharField(blank=True, max_length=20, verbose_name='图片编码')),
                ('v_no', models.SmallIntegerField(blank=True, default=0, verbose_name='册号')),
                ('v_page_no', models.SmallIntegerField(blank=True, default=0, verbose_name='pdf页码')),
                ('img_path', models.CharField(max_length=128, verbose_name='图片本地路径')),
                ('big_image', models.BooleanField(default=False, verbose_name='大图')),
                ('img_1200', models.BooleanField(default=False, verbose_name='1200图')),
                ('img_s3', models.BooleanField(default=False, verbose_name='上传到s3')),
                ('img_cropped', models.BooleanField(default=False, verbose_name='图片切列')),
                ('width', models.SmallIntegerField(blank=True, default=1200, verbose_name='图片宽度')),
                ('height', models.SmallIntegerField(blank=True, default=780, verbose_name='图片高度')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_path', models.CharField(max_length=128)),
                ('v_no', models.SmallIntegerField(blank=True, default=0)),
                ('pdf_page_offset', models.SmallIntegerField(blank=True, default=0)),
                ('total_page_no', models.SmallIntegerField(blank=True, default=0)),
                ('tripitaka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sutra.Tripitaka')),
            ],
        ),
        migrations.RemoveField(
            model_name='ocut',
            name='code',
        ),
        migrations.RemoveField(
            model_name='ocut',
            name='cut_data',
        ),
        migrations.RemoveField(
            model_name='ocut',
            name='page',
        ),
        migrations.RemoveField(
            model_name='page',
            name='col_no',
        ),
        migrations.RemoveField(
            model_name='page',
            name='column_ready',
        ),
        migrations.RemoveField(
            model_name='page',
            name='image_upload',
        ),
        migrations.RemoveField(
            model_name='page',
            name='ready',
        ),
        migrations.RemoveField(
            model_name='sutra',
            name='height',
        ),
        migrations.AddField(
            model_name='ocut',
            name='batch',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='sutra.Batch'),
        ),
        migrations.AddField(
            model_name='ocut',
            name='col_gened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ocut',
            name='col_no',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='ocut',
            name='col_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ocut',
            name='column_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ocut',
            name='cut_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ocut',
            name='cut_gened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ocut',
            name='cut_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ocut',
            name='v_no',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ocut',
            name='v_page_no',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='r_page_no',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='page',
            name='v_no',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='v_page_no',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
    ]
