# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-14 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sutra', '0019_auto_20180114_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oimg',
            options={'verbose_name': '图片', 'verbose_name_plural': '图片'},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'verbose_name': '册', 'verbose_name_plural': '册'},
        ),
    ]
