# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-14 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sutra', '0021_page_o_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocut',
            old_name='col_url',
            new_name='col_json',
        ),
        migrations.RenameField(
            model_name='ocut',
            old_name='cut_url',
            new_name='cut_json',
        ),
        migrations.AddField(
            model_name='ocut',
            name='cut_ori',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='o_cut',
            field=models.ForeignKey(blank=True, default='cee749df430448c9a6134c2915505be6', on_delete=django.db.models.deletion.CASCADE, to='sutra.OCut'),
            preserve_default=False,
        ),
    ]
