# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-14 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sutra', '0022_auto_20180114_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='sub_date',
            field=models.DateField(auto_now=True),
        ),
    ]
