# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-14 09:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sutra', '0024_auto_20180114_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': '批次', 'verbose_name_plural': '批次'},
        ),
        migrations.AlterModelOptions(
            name='ocut',
            options={'verbose_name': '切分数据', 'verbose_name_plural': '切分数据'},
        ),
        migrations.AlterField(
            model_name='batch',
            name='sub_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='date submitted'),
        ),
    ]
