# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-14 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sutra', '0025_auto_20180114_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocut',
            name='batch',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='sutra.Batch', verbose_name='所属批次'),
        ),
        migrations.AlterField(
            model_name='page',
            name='code',
            field=models.CharField(max_length=128, verbose_name='编码'),
        ),
        migrations.AlterField(
            model_name='page',
            name='img_path',
            field=models.CharField(max_length=128, verbose_name='s3图片路径'),
        ),
        migrations.AlterField(
            model_name='page',
            name='o_cut',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocut', to='sutra.OCut', verbose_name='切分'),
        ),
        migrations.AlterField(
            model_name='page',
            name='o_img',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sutra.OImg', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='page',
            name='r_page_no',
            field=models.SmallIntegerField(blank=True, default=1, verbose_name='卷页码'),
        ),
        migrations.AlterField(
            model_name='page',
            name='v_no',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='册号'),
        ),
        migrations.AlterField(
            model_name='page',
            name='v_page_no',
            field=models.SmallIntegerField(blank=True, default=1, verbose_name='页码'),
        ),
    ]
