# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-14 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sutra', '0026_auto_20180114_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='o_cut',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sutra.OCut', verbose_name='切分'),
        ),
    ]
